spring:
  profiles:
    active: default
  mvc:
    locale: ko_KR
    throw-exception-if-no-handler-found: true
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false